# Generated by Django 4.2.x on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.CharField(max_length=500),
        ),
    ]

