# Generated by Django 4.2.x on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supports_soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]

